### ISSUE TITLE
Configuration Manager Preview - software center connection bug

### ISSUE THREAD

**Issue by Mazto** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#10]
![admincenter](https://user-images.githubusercontent.com/44652433/127118992-75ef36f9-1698-4e8b-b334-5a2754be01e5.jpg)
I hope this is the correct place to post this.

We started to use admin center so we can control SCCM Remotely. This works great for sending updates ( Actions ). 

However if we klik on software center - options applications we can remotly install programs that need to be manuelly installed. 

For most computers this never works. It keeps loading but no data will show. The wierd thing is that the option Installation status will give us data but here we are unable to send installation instructions. 

Extra info 
This is for multiple source and destination computers, windows 10 fully updated and rebooted multiple times on diffrent days.

**Comment by prasidharora** [comment]
Thanks for reporting! I've passed this bug to the owning team :)

**Comment by RebeccaMbulaMs** [comment]
Closing this out as it is not owned by WAC :)
