### ISSUE TITLE
[WAC All Connections/Server Manager] - no display on filter by tag

### ISSUE THREAD

**Issue by closedstack** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#112]
**Gateway Version**: 1.3.2111.01001
**Extension Version** 2110

**To Reproduce**
1. Go to 'All Connections'
2. Click on 'Filters Drop Down'
3. The screen shows the count of number of objects expected to be shown for the filter, but does not show the computer objects themselves.

**Expected behavior**
All Computers matching the tag should be displayed

**Screenshots & Additional context**
![image](https://user-images.githubusercontent.com/10274541/148116646-97338c4c-2d6b-4661-ab54-66a27265d1a7.png)

![image](https://user-images.githubusercontent.com/10274541/148116738-c0dfd491-c1ea-482a-a0a6-786d6010665c.png)

**Comment by trungtran-msft** [comment]
This bug has been filed and is fixed internally. Expect a release in the near future with the fix.
