### ISSUE TITLE
when using search feature, it normally would filter the list on word typed.  the filtering works, (the number of items changes) but there are no items visible

### ISSUE THREAD

**Issue by gemidriver** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#128]
Version 2110
Build
1.3.2111.01001

**To Reproduce**
1. Go to 'main page - enter in search term
2. the total number if items wil be filtered
3. no items appear in the list

**Expected behavior**
Once the list is filtered you should be able to see the items

![image](https://user-images.githubusercontent.com/50426477/152912712-5bf2f0d2-58c6-480e-9ddc-4a0e73739ec5.png)
![image](https://user-images.githubusercontent.com/50426477/152912762-9c53b621-09e3-48d0-a43d-f128af3051b4.png)

**Comment by trungtran-msft** [comment]
We are aware of this issue and it has been fixed. Please expect a release with this fix in the near future.

**Comment by FDFessler** [comment]
AWESOME!  Thank You.
