### ISSUE TITLE
Event log erratic scrolling

### ISSUE THREAD

**Issue by erikdavids** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#132]
Version
2110
Build
1.3.2111.01001

**To Reproduce**
1. Connect to a PC
2. Click on Events > System
3. Scroll through the list.
4. Sometimes it only scrolls back up a few lines, other times it scrolls back to the top as you are trying to scroll down.

**Expected behavior**
Stop scrolling on release of the scroll bar or mouse wheel.

**Comment by ajm-nethunt** [comment]
encountering this constantly also - makes it practically unusable. Seems to occur in any browser [firefox, edge, brave, ...]

**Comment by RebeccaMbulaMs** [comment]
Hello,

We fixed this bug in our [latest release](https://aka.ms/wacdownload) :)

Thank you for raising it.
Kind regards,
Rebecca.
