### ISSUE TITLE
Hyper converged Cluster addition option is missing

### ISSUE THREAD

**Issue by pinakapogi** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#156]
When trying to add the Hyperconverged Cluster no option to add it 
![image](https://user-images.githubusercontent.com/103251028/162408461-461136d4-9872-4591-9d45-94c086e8a48a.png)

**Comment by RebeccaMbulaMs** [comment]
Hello @pinakapogi!
My name is Rebecca and I am a Product Manager at Microsoft.
I'd like to address this issue:
1. Once you see this menu, kindly select the "Add" option under the "Server clusters" tab
2. It should bring you to a screen like this where you can add your Hyperconverged cluster: 
![image](https://user-images.githubusercontent.com/96140637/163247738-23c01b03-e872-4f96-9c70-75d7fcc71bef.png)
3. WAC will automatically detect whether it is a hyperconverged cluster or not
Does this help? Kindly let me know :)

**Comment by pinakapogi** [comment]
Hi Rebecca,

I have several questions to confirm:

  1.  Is Nutanix deployed servers are compatible with Windows Admin Center?
  2.  Do I need to add servers on the hyperconverged cluster or just use the usual way?
  3.  Adding the servers in cluster way, do I have an option to control the Infra of Nutanix itself? Because I am confused what do you mean when I add the hyperconverged Infra. What will be my benefits?
Thanks

**Comment by RebeccaMbulaMs** [comment]
Hello @pinakapogi, 
Apologies for getting back to you later!
I am consulting with the team so that I can get back to you.
Will reopen the issue for now.
Kind regards
