### ISSUE TITLE
This application is using Azure AD Graph API, which is on a deprecation path message

### ISSUE THREAD

**Issue by teddimitrov** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#180]
**Gateway Version**: 1.3.2204.19002

**To Reproduce**
1. Go to the API permissions option in Azure for the registered Windows Admin Center app. 
2. At the top you will see the message:

_"This application is using Azure AD Graph API, which is on a deprecation path. Starting June 30th, 2020 we will no longer add any new features to Azure AD Graph API. We strongly recommend that you upgrade your application to use Microsoft Graph API instead of Azure AD Graph API to access Azure Active Directory resources"_

**Expected behavior**
Not to have that message/Windows Admin Center to use Microsoft Graph API instead of the soon to be deprecated Azure AD Graph API

**Screenshots & Additional context**
![Screenshot_1353](https://user-images.githubusercontent.com/55705230/169404062-f9a4209d-2e0f-44d7-991d-3be733bb6de9.png)

**Comment by prasidharora** [comment]
@teddimitrov We're aware of this and it will be resolved before Azure AD Graph is deprecated at the end of the year :)
