### ISSUE TITLE
Cant register with Azure

### ISSUE THREAD

**Issue by craftzneko** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#203]
**Gateway Version**: <Build number>
**Extension Version** that's been used if it applies

Email sent to your feedback address but created ticket here too

I am trying to register windows admin center to azure, but its failing. We are able to get through device authentication and it displays our tenant ID

1)	We have tried precreating the app registration from this guide [Configuring Azure Integration | Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/azure/azure-integration) when putting app ID into the form, connect remains greyed out with a red block symbol as the mouse
2)	We have tried creating by clicking on new and connect and we get the below error

 
![image](https://user-images.githubusercontent.com/662108/174288032-514a9be8-55e5-4b1e-aeeb-03580413f27b.png)

3)	We are running this as a tenant administrator account
4)	We have tired running direct from the gateway
5)	We have added the trusted sites required for EDGE
6)	We only have one tenant
7)	We have never tried the powershell script and have only tried using the gui
8)	We are running this version of WAC We are running this version of WAC  2110.2 Build 1.3.2204.19002
9)	We are running this on a server 2016 Standard

We are at a loss on how to make this work, or even find any meaningful logs to indicate where the issue is. Can you help?

**Comment by pr1malc0de** [comment]
Inside azure i see a success for authentication but also a failure that says. 	
For security reasons, user confirmation is required for this request. Please repeat the request allowing user interaction
