### ISSUE TITLE
Not displaying CPU or Memory usage for Azure Stack HCI Clusters

### ISSUE THREAD

**Issue by Grassyhopper** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#217]
**Gateway Version**: 1.3.2204.19002
I seem to be having an issue with our WAC gateway where all our Azure Stack HCI clusters CPU and Memory usage is 0 with a total of NaN%

**To Reproduce**
1. Click on a Azure Stack HCI cluster
2. Wait for the dashboard to load

**Expected behavior**
CPU and Memory usage to show and total to be correct

**Screenshots & Additional context**
![WAC NAN](https://user-images.githubusercontent.com/93753150/179653900-84a1fd33-f460-4a24-859f-f1cfd0ed3818.png)

**Comment by RebeccaMbulaMs** [comment]
Hi @Grassyhopper, 
I've filed a bug on this. Thank you for reporting it.
Kind regards!
Rebecca.

**Comment by Grassyhopper** [comment]
This issue was fixed with Windows update KB5017381
https://support.microsoft.com/en-us/topic/september-20-2022-non-security-update-kb5017381-b58ee96f-7ddb-4cfe-870e-5047cf2dd52d
