### ISSUE TITLE
Unable to remove computer connections

### ISSUE THREAD

**Issue by jlessenger-usdm** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#230]
**Gateway Version**: 2110.2
**Build**: 1.3.2204.19002

**To Reproduce**
Select computer connections and check items to delete and nothing happens.

**Comment by RebeccaMbulaMs** [comment]
Hello! I'm investigating this issue. Could you please more information? Preferably screenshots?

**Comment by jlessenger-usdm** [comment]
The issue I had was due to uploading an active directory file that was incorrectly formatted. I was unable to delete those connections from within Admin Center.
I’ve moved on using a different account so please close the bug ticket.
Thanks

**Comment by RebeccaMbulaMs** [comment]
Alright, thank you for the feedback!
