### ISSUE TITLE
[WAC] - Server cluster, cluster performance charts not loading

### ISSUE THREAD

**Issue by MANTiKA47** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#256]
**Gateway Version**: 2110.2
**Extension Version** that's been used if it applies

**To Reproduce**
1. Go to 'Any Server Cluster added'
2. Click on 'Dashboard'
3. Scroll down to 'Cluster Performance'
4. See error no error, chart is not loading

**Expected behavior**
A chart should be present with iops and latency data.

**Screenshots & Additional context**
We are using S2D clusters, on one of them the cluster performance chart is not showing anything. Configuration is the same on both, get-clusterperf is working on the cluster and with psremoting from the gateway to the cluster. Clusterperfhistory was stopped/started and ereased but still nothing shows up. All other metrics are working fine when browsing the cluster nodes.
![Capture](https://user-images.githubusercontent.com/115872961/195981179-221201c2-c5f5-4e8b-b862-626356e8b862.PNG)

**Comment by MANTiKA47** [comment]
Old wac installation files on the target cluster was found, after deleting it solved the problem.

**Comment by xzrians** [comment]
Face this issue also.

The way that i solved it by running command
`stop-ClusterPerformanceHistory -DeleteHistory`
`start-ClusterPerformanceHistory`

Using this command will delete ClusterPerformanceHistory volume and recreated back.


![image](https://github.com/MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback/assets/47202302/f262ae16-c743-4a2c-a4ee-255ec5c1479b)
