### ISSUE TITLE
Containers Extension - Cannot create new Conatiner Images on Server 2022 with WAC

### ISSUE THREAD

**Issue by AiDevAz** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#266]
WAC Version
2211 
WAC Build
1.4.2211.18002
Containers Extension 2.20.0

**To Reproduce**
Installed Azure Vanilla Server Image Windows Server 2022 Datacenter Build 20348.1249

Installed Docker and Containers throguh Windows Admin Center on Windows Server.
Pulled a Image from Dockerhub and wanted to create a new Image from the previous
downlaoded Image. (Look in the below picture)

![test001](https://user-images.githubusercontent.com/65558787/203786919-a1d497c0-70b0-42cc-a798-c1b26609dde2.png)

after hit build, We got following Error:
RemoteException: Cannot process command because a command is already specified with -Command or -EncodedCommand.
![test002](https://user-images.githubusercontent.com/65558787/203787464-3ebd9066-3a93-4b06-a547-1c46d14d3777.png)

Also note that the extensio also have some display issues, e.g displaying the downloaded images or the running containers.

**Expected behavior**
Build the Image with the specific parameters, but this will not happen.

**Comment by RebeccaMbulaMs** [comment]
Hello @AiDevAz,
Thank you for bringing this to our attention. This issue has been resolved and you should be able to get the fix on the local build of Windows Admin Center which you can download [using this link](https://aka.ms/wacdownload).
I am also part of the PM team for Windows Containers and OSS bridge tooling team would also like to know if I could connect with you to learn more about your usage of the containers tool in WAC? If this would be OK with you, please send me your available timings and timezone to rwambua@microsoft.com.
Kind regards,
Rebecca.
