### ISSUE TITLE
Cluster Manager cannot add cluster connections

### ISSUE THREAD

**Issue by meyj155** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#270]
**Gateway Version**: 1.3.2204.19002
**Extension Version** 2110.2

**To Reproduce**
1. Go to 'All Connections'
2. Click on drop down and select 'Cluster Manager'
3. Click '+ Add'
4. Enter the cluster name under 'Add cluster' in the right pane

**Expected behavior**
The Admin Center connects to the cluster and populates the cluster connection

**Screenshots & Additional context**
![cluster_error](https://user-images.githubusercontent.com/39279582/204918460-bc36a08a-190c-43dc-a904-23b99bd7083f.png)

**Comment by RebeccaMbulaMs** [comment]
Hello @meyj155,
I hope you are well.
Is this still an issue you are experiencing on the [latest build of WAC](https://aka.ms/wacdownload)?
Kind regards.
