### ISSUE TITLE
Containers extension - List of images and containers not being populated

### ISSUE THREAD

**Issue by prsliwa** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#273]
**Gateway Version**: 2110.2 / 1.3.2204.19002
**Extension Version**: 2.20.0

**To Reproduce**
I have running containers on Windows Server 2019 and they are visible on the Overview page but not under containers or images

**Expected behavior**
I should see the containers and images

**Screenshots & Additional context**
Overview:
![image](https://user-images.githubusercontent.com/11444225/205965802-2a600e2c-052a-4a7c-b4e4-322beb73523f.png)

Containers:
![image](https://user-images.githubusercontent.com/11444225/205965883-0682695f-6aac-4824-bf35-81559f145b75.png)

Images:
![image](https://user-images.githubusercontent.com/11444225/205965952-0c1d5a53-db20-4b03-a23a-15fb260a200a.png)

They are returned from the server, just not enumerated on the page:
![image](https://user-images.githubusercontent.com/11444225/205966483-383b306b-6cdb-47ce-9b3b-aca4001a4179.png)

Tested with Chrome (108.0.5359.94), Firefox (106.0.5 (64-bit)) and Edge (108.0.1462.42)

**Comment by RebeccaMbulaMs** [comment]
Hello @pvanderp and @prsliwa ,
Thank you for bringing this to our attention. This issue has been resolved and you should be able to get the fix on the local build of Windows Admin Center which you can download [using this link](https://aka.ms/wacdownload).
I am also part of the PM team for Windows Containers and OSS bridge tooling team would also like to know if I could connect with you to learn more about your usage of the containers tool in WAC and your organizational needs? If this would be OK with you, please send me your available timings and timezone to [rwambua@microsoft.com](mailto:rwambua@microsoft.com).
Kind regards,
Rebecca.
