### ISSUE TITLE
[Environment variables] - The list of Environment variables is not displayed on larger screens 

### ISSUE THREAD

**Issue by P-39-Airacobra** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#277]
**Windows Admin Center  Version**: 1.4.2212.08003

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect to a server.
2. Go to 'Settings' -> 'Environment variables'
3. See the list of variables is not populated even it says there are some items.
4. Make the browser window smaller until the list is populated.

**Screenshots & Additional context**
- It was working in v1.3.x
- Same results using Chrome/Brave/Edge
- Screenshots attached:

![Screenshot 1](https://user-images.githubusercontent.com/55145969/210559811-f080197a-7475-413b-8399-410a3d66f34b.jpg)
![Screenshot 2](https://user-images.githubusercontent.com/55145969/210559827-bc61618b-1c72-4786-925d-ebaf1f0eb868.jpg)

**Comment by RebeccaMbulaMs** [comment]
Hello, 

Thank you or bringing this up. I will investigate this.

Kind regards,
Rebecca.

**Comment by P-39-Airacobra** [comment]
Seems to be fixed. At least in the version 1.5.2306.14001.
