### ISSUE TITLE
[WAC] - Machine loading forever

### ISSUE THREAD

**Issue by OscarTheBard** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#278]
2211: 1.4.2212.08003

I'm trying to connect to any machine via WAC. 

**Expected behavior**
Succesful connection is established in WAC. I can use the machine.

**Screenshots & Additional context**
![wac](https://user-images.githubusercontent.com/76252412/212060094-21f58476-a38c-4af2-a53a-9147f6cf5bc8.PNG)

WinRM and PSRemoting is enabled. I can access all virtual machines using RDP, vmconnect or via local hyper-v manager with external servers connected to it. The following bug appeared after updating to 2211: 1.4.2212.08003.

**Comment by OscarTheBard** [comment]
![wac2](https://user-images.githubusercontent.com/76252412/212075824-5ec1cd73-ab2b-426b-af2f-af7d08ac9212.PNG)

**Comment by maparaschivei** [comment]
+1

I have the same issue and same error displayed in the dev tools console.

I cannot access any of the VM's through the VM "Connect" or "Download RDP file" options.

```
Version
2211

Build
1.4.2212.08003
```

**Comment by RebeccaMbulaMs** [comment]
Hi @maparaschivei and @OscarTheBard,

Are you still experiencing this issue on [our latest build](https://aka.ms/wacdownload)?

Kind regards,
Rebecca.

**Comment by OscarTheBard** [comment]
Hi, the problem resolved itself- probably by newer build.

Thanks

śr., 5 lip 2023, 06:31 użytkownik RebeccaMbulaMs ***@***.***>
napisał:

**Comment by RebeccaMbulaMs** [comment]
Hello,

Thanks so much for confirming this. Let me close this out.

Kind regards, 
Rebecca.
