### ISSUE TITLE
[WAC] - User with Gateway users rights gets Access Denied at WAC startpage

### ISSUE THREAD

**Issue by cde87** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#280]
**Gateway Version**: 2211 (1.4.2212.08003)

**To Reproduce**
1. If you open the WAC start page as user with gateway user rights then you get an Access Denied message.
![To1](https://user-images.githubusercontent.com/105430832/213742986-3edda882-e84c-4039-bcfd-16acaaaa696b.png)
2. If you change (with gateway user ritghts) the url from https://admincentersite to https://admincentersite/settings/account the site is visable (no Access Denied message)
![To2](https://user-images.githubusercontent.com/105430832/213742994-ac9fa398-2052-4050-8728-1ef4428d9735.png)
3. Changing to the sites "Server Manager", "Computer Management" and "Cluster Manager" is possible, these sites were shown correctly
![To3](https://user-images.githubusercontent.com/105430832/213743004-3d7e1689-0525-466f-9e91-323c56ab93af.png)
4. Changing to site "All connections" or clicking the button "Windows Admin Center" on the left generates the Access Denied message again.

This problem only exists with gateway user rights and since version 1.4.2212.08003.

**Comment by thesutex** [comment]
Same for us, stopped working after last WAC update

**Comment by skiewidt** [comment]
Same here - any update?

**Comment by RebeccaMbulaMs** [comment]
Hi @cde87, @thesutex and @skiewidt,

I apologize for this frustrating bug, is it still occurring in [our latest build](https://aka.ms/wacdownload)? If so, I will file a bug and bring it up.

Kind regards,
Rebecca.

**Comment by cde87** [comment]
Hi Rebecca,
with the latest build it worked.
