### ISSUE TITLE
Build 2110 Breaks Search Function

### ISSUE THREAD

**Issue by jledoux1962** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#68]
**Gateway Version**: 1.3.2111.01001

**To Reproduce**
1. From the All Connections tab, go to Search field.
2. Start typing connection name
3. All connections previously displayed disappear.

**Expected behavior**
Name of computer displayed as entered into Search field.

**Screenshots & Additional context**
I updated Windows Admin Center from 2103 to 2110.  Since the update, if I am on All Connections and start typing in the Search field, all displayed computer connections will disappear.

They will not come back until I click on either Server Management or Computer Management.

The Search function does work in Server Management and Computer Management.

**Comment by tddimitrov** [comment]
Same issue here - already filed this as a bug in "Connection list not displaying when searching or filtering by tag #61"
Hope it gets resolved soon...over ~1000 servers makes for a lot of scrolling...

**Comment by jensenjk** [comment]
same

**Comment by bswiento** [comment]
Same issues here when trying to search or filter with Edge or Firefox.  Version is 1.3.2111.01001

**Comment by jledoux1962** [comment]
Has there been any movement on this issue since the last post?

**Comment by Pseudoending** [comment]
Same issue here after updating to 2110, this is extremely debilitating, can this please be addressed?  

I am actively attempting to move our team over to use WAC and without the ability to simply perform a search for a server it makes the move to using WAC grind to a halt

**Comment by jledoux1962** [comment]
> Same issue here after updating to 2110, it seems that if I have a small list of servers the function works but if using a larger list or a shared connections list it entirely breaks. This is extremely debilitating, can this please be addressed?
> 
> I am actively attempting to move our team over to use WAC and without the ability to simply perform a search for a server it makes the move to using WAC grind to a halt

Today I updated to Version 2110.2 Build 1.3.2204.19002 and it appears to be fixed.  I will be testing it for the next few days and comment back if I find anything or run into any issues.

**Comment by Pseudoending** [comment]
> > Same issue here after updating to 2110, it seems that if I have a small list of servers the function works but if using a larger list or a shared connections list it entirely breaks. This is extremely debilitating, can this please be addressed?
> > I am actively attempting to move our team over to use WAC and without the ability to simply perform a search for a server it makes the move to using WAC grind to a halt
> 
> Today I updated to Version 2110.2 Build 1.3.2204.19002 and it appears to be fixed. I will be testing it for the next few days and comment back if I find anything or run into any issues.

Thank you for this update, hopefully they've resolved the issue and if so I can update to that version.  Is that a stable release?

**Comment by jledoux1962** [comment]
> > > Same issue here after updating to 2110, it seems that if I have a small list of servers the function works but if using a larger list or a shared connections list it entirely breaks. This is extremely debilitating, can this please be addressed?
> > > I am actively attempting to move our team over to use WAC and without the ability to simply perform a search for a server it makes the move to using WAC grind to a halt
> > 
> > 
> > Today I updated to Version 2110.2 Build 1.3.2204.19002 and it appears to be fixed. I will be testing it for the next few days and comment back if I find anything or run into any issues.
> 
> Thank you for this update, hopefully they've resolved the issue and if so I can update to that version. Is that a stable release?

Yes.  It should be available under the Settings > Updates section as a stable release.

**Comment by Pseudoending** [comment]
> > > > Same issue here after updating to 2110, it seems that if I have a small list of servers the function works but if using a larger list or a shared connections list it entirely breaks. This is extremely debilitating, can this please be addressed?
> > > > I am actively attempting to move our team over to use WAC and without the ability to simply perform a search for a server it makes the move to using WAC grind to a halt
> > > 
> > > 
> > > Today I updated to Version 2110.2 Build 1.3.2204.19002 and it appears to be fixed. I will be testing it for the next few days and comment back if I find anything or run into any issues.
> > 
> > 
> > Thank you for this update, hopefully they've resolved the issue and if so I can update to that version. Is that a stable release?
> 
> Yes. It should be available under the Settings > Updates section as a stable release.

Great, just updated and that does appear to have fixed the issue!  Thanks for the update on this!  

Now if only I could get the csv import to work properly, I'd be golden, haha

**Comment by RebeccaMbulaMs** [comment]
Hello :)

My name is Rebecca, Product Manager on Windows Admin Center. I'm very glad to hear that your issue on the search function was fixed.

What issue are you facing with CSV import?

Would you mind documenting this on a separate issue so that I can look into it?

Kind regards!
