### ISSUE TITLE
Search function broke in wac 2110 update

### ISSUE THREAD

**Issue by jensenjk** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#79]
when searching , previus version update search results as typing - in 2110 nothing happens until you have typed a servername excatly

**Comment by tddimitrov** [comment]
Same as #68 and #61 ...hope they resolve it promptly...

**Comment by fr0mtheinternet** [comment]
Unfortunately I don't get any results, regardless of entering a complete name. Additionally, the results stay blank even after clearing out the filter field and I either have to refresh the browser or click on Settings and then back again.

Interestingly whilst investigating this, I have found a way to get the search/filter functionality back again via some bizarre behaviour:
- Make sure All Connections is selected.
- Switch to Cluster or Computer Manager
- Switch to Server Manager
- Perform your search.

I only have entries in the Server list, so can't confirm behaviour for any other partition. So long as you remain on the server list, you can perform multiple searches. However, you must repeat the above steps if you return to the main list.

**Comment by trungtran-msft** [comment]
Thank you for finding this bizarre behavior for the workaround. 

Our dev team is currently working to fix this.

**Comment by shangles** [comment]
Also wanted to report that Search is broken (Firefox / Edge / Chrome)   I get the number of search results, but the page is blank

**Comment by FC-EricWeller** [comment]
In our environment the workaround doesn't seem to...err...work.

**Comment by FC-EricWeller** [comment]
Ah - Correction - the workaround does work if we have at least one tag defined.  We don't normally use tags but once we added one, name searches now work in Computer Management, Server Manager and Cluster Manager (but not in All Connections).

**Comment by gemidriver** [comment]
> Thank you for finding this bizarre behavior for the workaround.
> 
> Our dev team is currently working to fix this.

still an issue.. what is the update progress?

**Comment by trungtran-msft** [comment]
Yes, the search among other things is fixed in the public preview for 2110.2. You can read about it and download the build here: https://techcommunity.microsoft.com/t5/windows-admin-center-blog/windows-admin-center-version-2110-is-now-generally-available/ba-p/2911579

**Comment by gemidriver** [comment]
i already have that file downloaded and installed
on this version
2110
Build
1.3.2111.01001
search not working

**Comment by trungtran-msft** [comment]
@gemidriver That's the wrong MSI build. Are you sure that you downloaded it from the Windows Insider page?

**Comment by gemidriver** [comment]
I did - logged into the insider site and filled in details
Can the actual msi be provided?

Cheers
Brad

**Comment by tddimitrov** [comment]
Unable to initiate the download at the moment - 2 different browser display this (by now for 30+ minutes) while attempting to download 2110.2 preview... Have 1k+ servers and the search function fix is essential...

![Screenshot_1267](https://user-images.githubusercontent.com/93091027/162002018-1492fb95-2a58-488c-9468-f471a736c7ee.png)

**Comment by tddimitrov** [comment]
Update - was able to download the preview build and can confirm that search/filter works! Thank you to the developers!
