### ISSUE TITLE
Unable to list file shares

### ISSUE THREAD

**Issue by teddimitrov** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#8]
Using the latest version of the Files & file sharing extension - 1.240.0 and unable to list server file shares... Others are [reporting the issue](https://docs.microsoft.com/en-us/answers/questions/460580/windows-admin-center-file-shares.html) as well...

**Comment by trungtran-msft** [comment]
Hey @teddimitrov, 

I believe this is fixed in the latest extension version of 1.242.0. I am not able to reproduce this issue, can you please confirm on your environment?

Thank you, 
Trung

**Comment by teddimitrov** [comment]
@trungtran-msft 

Yes, I can confirm that the updated extension v. 1.241.0  (I don't see 1.242.0 yet as available) does indeed fix the issue. Thank you!

**Comment by trungtran-msft** [comment]
@teddimitrov 

Amazing, thank you so much :)
I'll close out this issue now.
