### ISSUE TITLE
[Hyper-V]  Installation of virtual switch failed during deploying Azure IoT edge Linux on Windows

### ISSUE THREAD

**Issue by arminghasemazar** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#9]
I'm using latest version of WAC and its extensions installed on the latest version of Windows Server 2019. Hyper-V has been installed and is running. When I deploy a new Azure IoT Edge for Linux on Windows on host (same PC) using default setting recommended by WAC, I ran into an error of "Error: Installation of virtual switch failed".

I already checked event viewer and below is what it shows:

```
Log Name:      Microsoft-ServerManagementExperience
Source:        UI
Date:          7/26/2021 12:35:46 PM
Event ID:      2
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      XXX
Description:
sessionId : 52a7f5bc-872c-4e95-ae8f-de9faa105039
eventId : Trace
level : Error
sourceName : Microsoft.AzureIoTEdge
source : EflowCreateWizard
timestamp : 1627295715557
message : DeployStepComponent
stack : 
moreEventData : 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="UI" />
    <EventID Qualifiers="0">2</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-07-26T10:35:46.173052100Z" />
    <EventRecordID>2590</EventRecordID>
    <Channel>Microsoft-ServerManagementExperience</Channel>
    <Computer>XXX</Computer>
    <Security />
  </System>
  <EventData>
    <Data>sessionId : 52a7f5bc-872c-4e95-ae8f-de9faa105039
eventId : Trace
level : Error
sourceName : Microsoft.AzureIoTEdge
source : EflowCreateWizard
timestamp : 1627295715557
message : DeployStepComponent
stack : 
moreEventData : </Data>
  </EventData>
</Event>
```

When I check Hyper-V manager, I can see that a virtual switch has already been made after I installed Hyper-V. So I don't see any error with Hyper-V. But clearly WAC cannot create a virtual switch that it apparently needs. Would you please help me find the solution?

**Comment by TerryWarwick** [comment]
@arminghasemazar.

This is an issue that we are aware of when deploying Azure EFLOW to Server that we are working on, it is not specific to either Windows Admin Center or the Azure IoT Edge (preview) extension.  Please join us over on the Azure EFLOW Github repository at https://aka.ms/azeflow-github and report your issue so that we can keep you abreast of an available solution that is coming very soon.

Terry Warwick
Microsoft

**Comment by RebeccaMbulaMs** [comment]
Hey!
Closing this issue as it is not WAC related :)
Kind regards!
