### ISSUE TITLE
[Tags] - Search tags not working

### ISSUE THREAD

**Issue by pyonchev** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#90]
**Gateway Version**: <1.3.2111.01001>

**To Reproduce**
1. Go to 'Search.'
2. write tag 
3. does not list any assets with that tag but count that there are some
![image](https://user-images.githubusercontent.com/41748471/143827482-b7ed6c15-3fa7-40e5-82d0-208957f3d33c.png)
![image](https://user-images.githubusercontent.com/41748471/143827563-791babef-bb97-4354-a065-85a74e59cb3b.png)

**Comment by mrjims1** [comment]
Same version searching for server name doesn't work for me too. It gets the correct count but doesn't display the results.

**Comment by BrysonRose** [comment]
Same issue we're having. The search doesn't work at all even without filters. As soon as anything is inputted to the search the list of computers goes blank.

**Comment by trungtran-msft** [comment]
Hello, this is a known issue with version 2110. We are releasing a public preview this Wednesday that you can try out. This build will have the fix in it.

**Comment by trungtran-msft** [comment]
Hello, our release is going to be delayed. In the meantime, you can try this private build with the fix.

Please understand that this build is not supported. We are still working on fixes and validation before the official GA.

Here is the build: https://microsoft-my.sharepoint-df.com/:u:/p/praror/EV_E1yve_b1KvHxkpTE3_YkBGfda_SMqMVCkNibjEi6h_g?e=4IEzpg&isSPOFile=1

**Comment by pyonchev** [comment]
Hi, 
Just updated to that build and tag search works. thanks! i will write if find any bug that are not features ;)
GL HF

**Comment by RebeccaMbulaMs** [comment]
Closing this as it has been fixed :)
