### ISSUE TITLE
Windows admin center login issues on Windows 11

### ISSUE THREAD

**Issue by davidtingcs** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#92]
Welcome to the Windows Admin Center debugging api. Type "MsftSme.help()" to see a list of available commands
api/settings/admin:1 
        
       Failed to load resource: the server responded with a status of 401 (Unauthorized)
api/gateway/status:1 
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
api/notifications/signalr/negotiate?clientProtocol=2.1&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1638352039447:1 
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
api/gateway/latestversion:1 
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
msftsme.core.a08bb227ba0bbc5f34f6.js:1 msft.sme.shell -- Notification

**Comment by trungtran-msft** [comment]
Hey @davidtingcs, 

Can you please share the login issue on Windows 11? There's not much I can do on my side this information you have above because I cannot repro it on my environment.

**Comment by davidtingcs** [comment]
Hi Support,

[image: image.png]

**Comment by trungtran-msft** [comment]
Your comment doesn't have anything of substance in it. I'm going to close this issue now, please reopen another one with all the information outlined in the template if you'd like to have us look at it.
